# Generated by Django 4.2.27 on 2026-01-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=255)),
                ('cooking_time', models.IntegerField(help_text='In minutes')),
                ('difficulty', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
